version: 0.2

phases:
  install-dependencies:
    runtime-versions:
      python: 3.9

    commands:
      - pip install --upgrade awscli \
        botocore \
        boto3 \
        pyyaml \
        sagemaker==2.132.0

  run-spark-job:
    commands:
      - python run/run_spark_job.py

  run-training-job:
    commands:
      - python run/run_training_job.py



