version: 0.2

phases:
  install-dependencies:
    runtime-versions:
      python: 3.9

    commands:
      - pip install --upgrade boto3 \
        pyyaml \
        sagemaker==2.132.0

  run-makefile:
    commands:
      - make all



